/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RedisChat;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.HashMap;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JOptionPane;
import redis.clients.jedis.Jedis;
import redis.clients.jedis.JedisPool;

/**
 *
 * @author USUARIO
 */
public class VentanaCliente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCliente
     */
    public static HashMap<String, String> canalesSuscritos = new HashMap<>();
    public static HashMap<String, Subscriber2> subscriberCanales = new HashMap<>();
    public static final String channel_name = "redisChannel";
    public static boolean validaVerMsj = false;
    private static String IpServidor = null;
    private static final Subscriber2 subscriber = new Subscriber2();
    private static Jedis subscriberJedis = null;
    private static JedisPool jedispool;

    public VentanaCliente() {
        initComponents();
        Font font;
        font = new Font("Tempus Sans ITC", Font.BOLD, 16);

        nombreCanalField.setFont(font);
        nombreUsuariolField.setFont(font);

    }

    public Image getIconImage() {
        Image retValeu = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo.jpe"));
        return retValeu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suscribirCrearDialog = new javax.swing.JDialog();
        suscribirBoton = new javax.swing.JButton();
        crearGrupoBoton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        crearDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreUsuariolField = new javax.swing.JTextField();
        nombreCanalField = new javax.swing.JTextField();
        aceptarCrearGrupoBoton = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        suscribirCrearDialog.setTitle("Suscribir/Crear");
        suscribirCrearDialog.setUndecorated(true);
        suscribirCrearDialog.setResizable(false);
        suscribirCrearDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        suscribirBoton.setBackground(new java.awt.Color(0, 51, 51));
        suscribirBoton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        suscribirBoton.setForeground(new java.awt.Color(255, 255, 255));
        suscribirBoton.setText("Suscribirse");
        suscribirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suscribirBotonActionPerformed(evt);
            }
        });
        suscribirCrearDialog.getContentPane().add(suscribirBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 130, -1));

        crearGrupoBoton.setBackground(new java.awt.Color(0, 102, 102));
        crearGrupoBoton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        crearGrupoBoton.setForeground(new java.awt.Color(255, 255, 255));
        crearGrupoBoton.setText("Crear Grupo");
        crearGrupoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearGrupoBotonActionPerformed(evt);
            }
        });
        suscribirCrearDialog.getContentPane().add(crearGrupoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Suscribirse/Crear Grupo");
        suscribirCrearDialog.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jButton6.setBackground(new java.awt.Color(0, 51, 51));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        suscribirCrearDialog.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 130, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menucrear_opt.jpg"))); // NOI18N
        suscribirCrearDialog.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        crearDialog.setUndecorated(true);
        crearDialog.setResizable(false);
        crearDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Crear Grupo");
        crearDialog.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre del Canal:");
        crearDialog.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre de Usuario:");
        crearDialog.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        crearDialog.getContentPane().add(nombreUsuariolField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 174, -1));

        nombreCanalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCanalFieldActionPerformed(evt);
            }
        });
        crearDialog.getContentPane().add(nombreCanalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 174, -1));

        aceptarCrearGrupoBoton.setBackground(new java.awt.Color(0, 51, 51));
        aceptarCrearGrupoBoton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        aceptarCrearGrupoBoton.setForeground(new java.awt.Color(255, 255, 255));
        aceptarCrearGrupoBoton.setText("Aceptar");
        aceptarCrearGrupoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarCrearGrupoBotonActionPerformed(evt);
            }
        });
        crearDialog.getContentPane().add(aceptarCrearGrupoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jButton8.setBackground(new java.awt.Color(0, 51, 51));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Cancelar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        crearDialog.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/creargrupo_opt.jpg"))); // NOI18N
        crearDialog.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 450));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RedisChat");
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenidos a RedisChat");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 40));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Suscribirse/Crear Grupo de Chat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 315, -1));

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ver Grupos Suscritos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 315, -1));

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Información");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 315, -1));

        jButton5.setBackground(new java.awt.Color(0, 51, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 187, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        suscribirCrearDialog.setSize(420, 430);
        suscribirCrearDialog.setResizable(false);
        suscribirCrearDialog.setLocationRelativeTo(null);
        suscribirCrearDialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        suscribirCrearDialog.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void suscribirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suscribirBotonActionPerformed
        // TODO add your handling code here:
        VentanaSuscribir v = new VentanaSuscribir(IpServidor, canalesSuscritos, subscriberCanales);
        v.setLocationRelativeTo(null);
        v.setVisible(true);
        suscribirCrearDialog.dispose();
    }//GEN-LAST:event_suscribirBotonActionPerformed

    private void aceptarCrearGrupoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarCrearGrupoBotonActionPerformed
        // TODO add your handling code here:
        final String canalNuevo = nombreCanalField.getText().toString();
        String nombreUsuario = nombreUsuariolField.getText().toString();
        if (!canalNuevo.isEmpty() && !nombreUsuario.isEmpty()) {
            String canal_verificacion = (String) canalesSuscritos.get(canalNuevo);
            if (canal_verificacion != null) {
                System.out.println("Ud ya se encuentra registrado a este grupo");
                JOptionPane.showMessageDialog(null, "Ya se encuentra registrado a un grupo con  este nombre", "Error", JOptionPane.ERROR_MESSAGE);
            } else {

                subscriberCanales.put(canalNuevo, subscriber);
                canalesSuscritos.put(canalNuevo, nombreUsuario);
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        try {

                            subscriberJedis.subscribe(subscriber, (String) canalNuevo);

                        } catch (Exception e) {
                            System.out.println("Subscribing failed." + e);
                        }
                    }
                }).start();
                crearDialog.dispose();
                suscribirCrearDialog.dispose();
                JOptionPane.showMessageDialog(null, "Se creo el nuevo canal de chat con exito");

                System.out.println("Subscricion terminada a: " + canalNuevo);
            }
        }
        else {
        System.out.println("Porfavor Ingrese valores en los dos campos");
                JOptionPane.showMessageDialog(null, "Ingrese valores tanto en nombre del grupo como de usuario", "Error", JOptionPane.ERROR_MESSAGE);
           
        }
    }//GEN-LAST:event_aceptarCrearGrupoBotonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        crearDialog.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void crearGrupoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearGrupoBotonActionPerformed
        // TODO add your handling code here:
        crearDialog.setSize(420, 430);
        crearDialog.setResizable(false);
        crearDialog.setLocationRelativeTo(null);
        crearDialog.setVisible(true);

        suscribirCrearDialog.dispose();
    }//GEN-LAST:event_crearGrupoBotonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        VentanaVerGrupos v = new VentanaVerGrupos(canalesSuscritos, jedispool);
        v.setLocationRelativeTo(null);
        v.setResizable(false);
        v.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        VentanaInfo v = new VentanaInfo();
        v.setLocationRelativeTo(null);
        v.setResizable(false);
        v.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void nombreCanalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCanalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCanalFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        IpServidor = args[0];
        jedispool = new JedisPool(IpServidor);
        subscriberJedis = jedispool.getResource();
        HashMap<String, String> canalesSub = new HashMap<String, String>();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaCliente v = new VentanaCliente();;

                v.setLocationRelativeTo(null);
                v.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarCrearGrupoBoton;
    private javax.swing.JDialog crearDialog;
    private javax.swing.JButton crearGrupoBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nombreCanalField;
    private javax.swing.JTextField nombreUsuariolField;
    private javax.swing.JButton suscribirBoton;
    private javax.swing.JDialog suscribirCrearDialog;
    // End of variables declaration//GEN-END:variables
}
