/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RedisChat;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import redis.clients.jedis.Jedis;
import redis.clients.jedis.JedisPool;

/**
 *
 * @author USUARIO
 */
public class VentanaCliente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCliente
     */
    public static HashMap<String, String> canalesSuscritos = new HashMap<>();
    public static HashMap<String, Subscriber2> subscriberCanales = new HashMap<>();
    public static final String channel_name = "redisChannel";
    public static boolean validaVerMsj=false;
    private static String IpServidor=null;
    private static final Subscriber2 subscriber = new Subscriber2();
    private static Jedis subscriberJedis = null;
    private static JedisPool jedispool;
    
    public VentanaCliente() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suscribirCrearDialog = new javax.swing.JDialog();
        suscribirBoton = new javax.swing.JButton();
        crearGrupoBoton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        crearDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreUsuariolField = new javax.swing.JTextField();
        nombreCanalField = new javax.swing.JTextField();
        aceptarCrearGrupoBoton = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        suscribirCrearDialog.setTitle("Suscribir/Crear");
        suscribirCrearDialog.setResizable(false);

        suscribirBoton.setBackground(new java.awt.Color(51, 204, 255));
        suscribirBoton.setText("Suscribirse");
        suscribirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suscribirBotonActionPerformed(evt);
            }
        });

        crearGrupoBoton.setBackground(new java.awt.Color(51, 204, 255));
        crearGrupoBoton.setText("Crear Grupo");
        crearGrupoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearGrupoBotonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel2.setText("Suscribirse a Grupo o Crear uno");

        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout suscribirCrearDialogLayout = new javax.swing.GroupLayout(suscribirCrearDialog.getContentPane());
        suscribirCrearDialog.getContentPane().setLayout(suscribirCrearDialogLayout);
        suscribirCrearDialogLayout.setHorizontalGroup(
            suscribirCrearDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suscribirCrearDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(suscribirCrearDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(suscribirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearGrupoBoton))
                .addGap(122, 122, 122))
            .addGroup(suscribirCrearDialogLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(suscribirCrearDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21))
        );
        suscribirCrearDialogLayout.setVerticalGroup(
            suscribirCrearDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suscribirCrearDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(suscribirBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crearGrupoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        crearDialog.setResizable(false);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel3.setText("Crear Grupo");

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Nombre del Canal:");

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Nombre de Usuario:");

        aceptarCrearGrupoBoton.setText("Aceptar");
        aceptarCrearGrupoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarCrearGrupoBotonActionPerformed(evt);
            }
        });

        jButton8.setText("Cancelar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crearDialogLayout = new javax.swing.GroupLayout(crearDialog.getContentPane());
        crearDialog.getContentPane().setLayout(crearDialogLayout);
        crearDialogLayout.setHorizontalGroup(
            crearDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearDialogLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(crearDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(nombreUsuariolField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreCanalField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearDialogLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aceptarCrearGrupoBoton)
                .addGap(21, 21, 21))
        );
        crearDialogLayout.setVerticalGroup(
            crearDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreCanalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreUsuariolField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crearDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarCrearGrupoBoton)
                    .addComponent(jButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RedisChat");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenidos a RedisChat :)");

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setText("Suscribirse/Crear Grupo de Chat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 204, 255));
        jButton2.setText("Ver Grupos Suscritos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 204, 255));
        jButton3.setText("Información");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 204, 255));
        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addGap(31, 31, 31)
                .addComponent(jButton3)
                .addGap(30, 30, 30)
                .addComponent(jButton5)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        suscribirCrearDialog.setSize(351, 220);
        suscribirCrearDialog.setResizable(false);
        suscribirCrearDialog.setLocationRelativeTo(null);
        suscribirCrearDialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        suscribirCrearDialog.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void suscribirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suscribirBotonActionPerformed
        // TODO add your handling code here:
        VentanaSuscribir v = new VentanaSuscribir(IpServidor,canalesSuscritos,subscriberCanales);
        v.setLocationRelativeTo(null);
        v.setVisible(true);
        suscribirCrearDialog.dispose();
    }//GEN-LAST:event_suscribirBotonActionPerformed

    private void aceptarCrearGrupoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarCrearGrupoBotonActionPerformed
        // TODO add your handling code here:
        final String canalNuevo = nombreCanalField.getText().toString();
        String nombreUsuario = nombreUsuariolField.getText().toString();
        if(!canalNuevo.isEmpty() && !nombreUsuario.isEmpty()){
            String canal_verificacion = (String) canalesSuscritos.get(canalNuevo);
            if (canal_verificacion != null) {
                System.out.println("Ud ya se encuentra registrado a este grupo");
                JOptionPane.showMessageDialog(null, "Ya se encuentra registrado a un grupo con  este nombre", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                
                subscriberCanales.put(canalNuevo, subscriber);
                canalesSuscritos.put(canalNuevo, nombreUsuario);
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        try {

                            subscriberJedis.subscribe(subscriber, (String) canalNuevo);
                            

                        } catch (Exception e) {
                            System.out.println("Subscribing failed." + e);
                        }
                    }
                }).start();
                crearDialog.dispose();
                suscribirCrearDialog.dispose();
                JOptionPane.showMessageDialog(null, "Se creo el nuevo canal de chat con exito");
                
                System.out.println("Subscricion terminada a: " + canalNuevo);
            }
        }
    }//GEN-LAST:event_aceptarCrearGrupoBotonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        crearDialog.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void crearGrupoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearGrupoBotonActionPerformed
        // TODO add your handling code here:
        crearDialog.setSize(351, 279);
        crearDialog.setResizable(false);
        crearDialog.setLocationRelativeTo(null);
        crearDialog.setVisible(true);
        suscribirCrearDialog.dispose();
    }//GEN-LAST:event_crearGrupoBotonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        VentanaVerGrupos v = new VentanaVerGrupos(canalesSuscritos,jedispool);
        v.setLocationRelativeTo(null);
        v.setResizable(false);
        v.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Implementar Información
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        IpServidor = args[0];
        jedispool = new JedisPool(IpServidor);
        subscriberJedis = jedispool.getResource();
        HashMap<String,String> canalesSub = new HashMap<String,String>();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaCliente v= new VentanaCliente();;
                        
                v.setLocationRelativeTo(null);
                v.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarCrearGrupoBoton;
    private javax.swing.JDialog crearDialog;
    private javax.swing.JButton crearGrupoBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombreCanalField;
    private javax.swing.JTextField nombreUsuariolField;
    private javax.swing.JButton suscribirBoton;
    private javax.swing.JDialog suscribirCrearDialog;
    // End of variables declaration//GEN-END:variables
}
