/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RedisChat;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListSelectionModel;
import redis.clients.jedis.Jedis;

/**
 *
 * @author USUARIO
 */
public class VentanaChat extends javax.swing.JFrame {

    private final Jedis publisherJedis;
    private final String nombreCanal;
    private final String nombreUsuario;
    public DefaultListModel listModel;
    private Component padre;

    public DefaultListModel getListModel() {
        return listModel;
    }

    /**
     * Creates new form VentanaChat
     */
    public VentanaChat(ArrayList<String> mensajes, Jedis publisherJedis, String canal, String usuario, Component padre) throws IOException {
        this.publisherJedis = publisherJedis;
        this.nombreCanal = canal;
        this.nombreUsuario = usuario;
        this.padre = padre;
        this.setTitle(canal);
        initComponents();
        this.nombreUsuarioLabel.setText(usuario);
        nombreGrupoLabel.setText(canal);
        listModel = new DefaultListModel();
        if (mensajes != null) {
            int longitud = mensajes.size();

            for (String mensaje : mensajes) {
                listModel.addElement(mensaje);
            }

        }
        jList1 = new JList(listModel);
        Font font;
        font = new Font("Tempus Sans ITC", Font.BOLD, 14);
        Font font2;
        font2 = new Font("Tempus Sans ITC", Font.BOLD, 14);
        jList1.setFont(font);
        jList1.setBackground(Color.DARK_GRAY);
        jList1.setForeground(Color.WHITE);
        jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jList1);
        mensajeTextArea.setFont(font);

    }

    public Image getIconImage() {
        Image retValeu = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo.jpe"));
        return retValeu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreGrupoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        mensajeTextArea = new javax.swing.JTextArea();
        Enviar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nombreUsuarioLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setIconImage(getIconImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Grupo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        nombreGrupoLabel.setBackground(new java.awt.Color(0, 51, 51));
        nombreGrupoLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        nombreGrupoLabel.setForeground(new java.awt.Color(204, 255, 255));
        nombreGrupoLabel.setText("Nombre del Grupo");
        getContentPane().add(nombreGrupoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 244, -1));

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 420, 180));

        mensajeTextArea.setColumns(20);
        mensajeTextArea.setRows(5);
        mensajeTextArea.setAutoscrolls(false);
        mensajeTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mensajeTextAreaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(mensajeTextArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 420, 40));

        Enviar.setBackground(new java.awt.Color(0, 51, 51));
        Enviar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Enviar.setForeground(new java.awt.Color(255, 255, 255));
        Enviar.setText("Enviar");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });
        getContentPane().add(Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        nombreUsuarioLabel.setBackground(new java.awt.Color(0, 51, 51));
        nombreUsuarioLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        nombreUsuarioLabel.setForeground(new java.awt.Color(204, 255, 255));
        nombreUsuarioLabel.setText("Nombre de usuario");
        getContentPane().add(nombreUsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 244, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chats_opt.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        // TODO add your handling code here:
        String mensaje = mensajeTextArea.getText().toString();
        if (!mensaje.isEmpty() && !(mensaje.equals("\n"))) {
            publisherJedis.publish(nombreCanal, nombreUsuario + ": " + mensaje);
            mensajeTextArea.setText("");
            //listModel.addElement(nombreUsuario+":"+ mensaje);
        } else {
            mensajeTextArea.setText("");
        }

    }//GEN-LAST:event_EnviarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VentanaVerGrupos.chats.remove(nombreCanal);
        this.dispose();
        padre.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        VentanaVerGrupos.chats.remove(nombreCanal);
           padre.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void mensajeTextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mensajeTextAreaKeyTyped
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            Enviar.doClick();
        }
     }//GEN-LAST:event_mensajeTextAreaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea mensajeTextArea;
    private javax.swing.JLabel nombreGrupoLabel;
    private javax.swing.JLabel nombreUsuarioLabel;
    // End of variables declaration//GEN-END:variables
}
